id: A0E60840E
title: 'Words of Truth: An Aspiration for the Spread of the Noble Gendenpa Tradition'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:32:05.576708
  last_modified_at: 2022-03-01 00:32:05.576714
